version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    expose:
      - "27017"

  web:
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    volumes:
      - uploaded-files:/storage
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
      OPENAI_KEY_2: ${OPENAI_KEY_2}

  nodejs_worker:
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
      OPENAI_KEY_2: ${OPENAI_KEY_2}

  python_worker:
    build: ./workers
    depends_on:
      - redis
      - mongodb
    volumes:
      - uploaded-files:/storage
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
      OPENAI_KEY_2: ${OPENAI_KEY_2}

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web

  widget:
    build: ./widget
    ports:
      - "3031:80"
    depends_on:
      - web

volumes:
  db-data:
    driver: local
  uploaded-files:
    driver: local